#!/usr/bin/bash

cd "$HOME" || exit 1

SRC="$HOME/Revancify"

DATA="$SRC/data"
[ -e "$DATA" ] || mkdir -p "$DATA"

BIN="$PREFIX/bin"

HELP="revancify

Usage: revancify [OPTION]

Options:
-u:  Disable Update Check
-r:  Disable Root access
-v:  Print current version
-h:  Print help statement"

while getopts ":urvh" OPT 2> /dev/null; do
    case $OPT in
        u)
            INTERNET_ACCESS=false
            ;;
        r)
            ROOT_ACCESS=false
            ;;
        v)
            source "$SRC/.info"
            echo "$VERSION"
            exit
            ;;
        h)
            echo -e "$HELP"
            exit
            ;;
        ?)
            echo -e "Invalid option specified: -${OPTARG}"
            echo -e "$HELP"
            exit 1
            ;;
    esac
done

terminate() {
    killall -9 curl &> /dev/null
    killall -9 wget &> /dev/null
    clear
    echo "Script terminated !!"
    tput cnorm
    exit 1
}
trap terminate SIGTERM SIGINT SIGABRT

installDependencies() {
    echo "Checking dependencies..."

    [ -e "$HOME/storage" ] || termux-setup-storage

    BINS=$(ls "$BIN")
    grep -q java <<< "$BINS" || PKGS+=("openjdk-21")
    grep -q wget <<< "$BINS" || PKGS+=("wget")
    grep -q tput <<< "$BINS" || PKGS+=("ncurses-utils")
    grep -q dialog <<< "$BINS" || PKGS+=("dialog")
    grep -q pup <<< "$BINS" || PKGS+=("pup")
    grep -q jq <<< "$BINS" || PKGS+=("jq")
    grep -q unzip <<< "$BINS" || PKGS+=("unzip")

    if [ "${#PKGS[@]}" -ne 0 ]; then
        pkg update -o Dpkg::Options::="--force-confnew" || return 1
        pkg install "${PKGS[@]}" -y -o Dpkg::Options::="--force-confnew" || return 1
    fi

    sed -i '/allow-external-apps/s/# //' "$HOME/.termux/termux.properties"

    CTR=0 && while [ ! -e "$DATA/aapt2" ]; do
        [ $CTR -gt 2 ] && return 1
        readarray -t RESPONSE < <(curl -s "https://api.github.com/repos/someone5678/revanced-aapt2/releases/latest" | jq -r --arg ARCH "$(getprop ro.product.cpu.abi)" '.assets[] | if (.name | test($ARCH)) then (.browser_download_url, .size) else empty end' 2> /dev/null)
        [ "${#RESPONSE[@]}" -eq 0 ] && return 1
        wget "${RESPONSE[0]}" -O "$DATA/aapt2"
        chmod +x "$DATA/aapt2"
        if [ "${RESPONSE[1]}" == "$(stat -c%s "$DATA/aapt2" 2> /dev/null)" ]; then
            break
        else
            rm "$DATA/aapt2"
        fi
        (( CTR++ ))
    done
    unset RESPONSE
    CTR=0 && while [ ! -e "$DATA/ApkEditor.jar" ]; do
        [ $CTR -gt 2 ] && return 1
        readarray -t RESPONSE < <(curl -s "https://api.github.com/repos/REAndroid/APKEditor/releases/latest" | jq -r '.assets[0] | .browser_download_url, .size' 2> /dev/null)
        [ "${#RESPONSE[@]}" -eq 0 ] && return 1
        wget "${RESPONSE[0]}" -O "$DATA/ApkEditor.jar"
        if [ "${RESPONSE[1]}" == "$(stat -c%s "$DATA/ApkEditor.jar" 2> /dev/null)" ]; then
            break
        else
            rm "$DATA/ApkEditor.jar"
        fi
        (( CTR++ ))
    done

    return 0
}

fetchSrc() {
    [ -e "$SRC/.info" ] && source "$SRC/.info"

    [ "$INTERNET_ACCESS" == false ] && return

    ping -c 1 google.com &> /dev/null || return

    if [ ! -d Revancify ]; then
        echo "Installing Revancify..."
        if ! git clone https://github.com/someone5678/Revancify.git; then
            echo -e "Unable to install Revancify !!\nPlease try again with proper Internet"
            exit 1
        fi
    else
        echo "Checking update..."
        cd Revancify
        if ! git fetch origin; then
            echo -e "Unable to update Revancify !!\nPlease try again with proper Internet"
            cd
            exit 1
        else
            echo "Updating Revancify..."
            git reset --hard origin/main
        fi
    fi
}

clear

if ! installDependencies; then
    echo -e "Dependencies not installed !!\nRun again with stable internet connection."
    exit 1
fi

fetchSrc

if [ "$ROOT_ACCESS" != false ] && su -c 'exit' &> /dev/null ; then
    ROOT_ACCESS=true
else
    ROOT_ACCESS=false
fi

cd "$DATA" &> /dev/null || exit 1

tput civis

bash $(case $- in (*x*) printf %s -x ;; esac) "$SRC/main.sh" "$ROOT_ACCESS"
EXIT_CODE=$?

tput cnorm
clear

exit "$EXIT_CODE"
